server:
    port: 8080
    servlet:
        context-path: /cozyCats

spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 123956374047-vcths0ceg9jbcoltsrmfehgrpe8msm5j.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                            - email
                            - profile
    main:
        allow-circular-references: 'true'
    datasource:
        url: jdbc:mysql://localhost:3306/cozycatsdb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL8Dialect
                    format_sql: true
            show-sql: true


